### PR TITLE
WIP on restructuring to be less intrusive

### PR DESCRIPTION
**Pull request by notahat**
Discuss.

### CODE REVIEW

**Comment by warrenseen** [comment]
@notahat is this ready to go? Just wondering if I should merge it into #10 first?

**Comment by notahat** [comment]
Not really ready to go, given it's incomplete and untested. Happy to bash it into shape over the weekend if you're keen to use it.

**Comment by warrenseen** [comment]
@notahat no problem, nothing there we particularly need yet, but I just thought I should check since I'm trying to isolate the references to the S3 hostname.

**Comment by dgoodlad** [comment]
:+1:

**Pull request merged**
